language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: KK7ZhpllhgQqPoQZuE2m8AhjnJqXg2D16gvR4LIWtMoRVM3OKlTZPGiV6PxGnAOTqqCA9Nx5KGfEMRUddF8SUZ0uE4akuKjsMuZNktZb7cfjfS6DjcnBKY+YsVTGZvERZCeQk27QB+yBqnFr4kXgCjIyPNCbX1ugzL1cScKwXQU=
  - secure: cLXqU4T5Y7b0YZ+hEGs7mbiC1mw7u5SGzV7kE7yUCuojYqfCp41H1O/8q4mUCusDgFj4tCgXzyCIft0zw38st1rtc9iOutz2U5Wc0Cy+npPKx43yPiOg4/HsbyH1NCRTqGpLfKNx2PSKlhwIk12z1I1duXu8Ysb8NbcoFE0NZR8=
  - secure: UjtJGsvBH9+bO7T2Ve8pcXzJm/BDQir9kwwlCW2ALwIGcHhiI7EAsJYx9OGj4+HvtQxOGyuHAvZP+atlMf89UGhfFCdrc+ck7FmBpKbxGJMnjKUIHbfXk9E9mv7c1gq7klrfQWja4fGq1jBKFFnfGSvrRIBIb8nYoqBOFxk1abg=
notifications:
  slack:
    secure: Ecr/TeV9dMhmZFWPpnhgPyHsn2R029fwqlh7rQhYB+SbreARu9Dp4nl3ALeQ4ci8TzsXUTM47t7lKrgl5eIi8AgajYtml27NMupmaa0vFFWclj8i8DpGXlqmYywlltHofcOBlZ7b8yVm3wge0Ymyc37NwENQOjTvUvDOzW3RMiM=
